### ISSUE TITLE
Objeto 3D

### ISSUE THREAD

**Issue by IsraelNicolas61** [SistemasTecTlaxiaco/actividad-4-diseno-de-objeto-3d-en-blender-equipo-balam#1]
[Practica 4 RA.pdf](https://github.com/SistemasTecTlaxiaco/actividad-4-diseno-de-objeto-3d-en-blender-equipo-balam/files/11124708/Practica.4.RA.pdf)

**Comment by josealfredo79** [comment]
Calificacion

**Comment by josealfredo79** [comment]
Calificacion 20
